#!/usr/bin/env python3
# make_card_art.py -- the controller card (a8r_card.c), from
# tools/card/labeledcontroller.png: the Pro Controller with its numbered
# callouts, on transparency. Cropped to what it draws, its faint
# background-removal haze dropped (alpha < 40), scaled (premultiplied, area-
# averaged) to fit one 600 x 480 diagram of the game's card texture, centred,
# and written as an RGBA PNG into source/a8r_card_art.h. Run from anywhere.
import io, os
from PIL import Image

W, H = 600, 480
here = os.path.dirname(os.path.abspath(__file__))
src = Image.open(os.path.join(here, 'labeledcontroller.png')).convert('RGBA')
r, g, b, a = src.split()
a = a.point(lambda v: 0 if v < 40 else v)
src = Image.merge('RGBA', (r, g, b, a))
src = src.crop(a.getbbox())
k = min(W / src.width, H / src.height)
size = (round(src.width * k), round(src.height * k))
art = src.convert('RGBa').resize(size, Image.BOX).convert('RGBA')
card = Image.new('RGBA', (W, H), (0, 0, 0, 0))
card.paste(art, ((W - size[0]) // 2, (H - size[1]) // 2))
buf = io.BytesIO()
card.save(buf, 'PNG', optimize=True)
data = buf.getvalue()
out = os.path.join(here, '..', '..', 'source', 'a8r_card_art.h')
with open(out, 'w') as f:
    f.write('/* a8r_card_art.h -- generated by tools/card/make_card_art.py from\n'
            ' * tools/card/labeledcontroller.png: the controller card, one %d x %d\n'
            ' * diagram, RGBA PNG. */\n' % (W, H))
    f.write('#define A8R_CARD_ART_W %d\n#define A8R_CARD_ART_H %d\n' % (W, H))
    f.write('static const unsigned char k_card_art_png[%d] = {\n' % len(data))
    for i in range(0, len(data), 20):
        f.write('    ' + ', '.join('0x%02x' % v for v in data[i:i + 20]) + ',\n')
    f.write('};\n')
print('%s: %dx%d art in a %dx%d diagram, %d bytes of PNG' % (os.path.normpath(out), size[0], size[1], W, H, len(data)))
