/* a8r_menu_texts.h -- the mod's What's New, Help and About pages as lists of its
 * string resources (their words come from A8R.apk at run time, a8r_arsc.c):
 * sizes (sp), colours and gaps (dp) from its layouts saveload_dialog_{whatsnew,
 * help,about}.xml. Included by a8r_menu.c. */
static const Item k_whatsnew[] = {
    {IT_TEXT, "saveload_whats_new_title1", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title1_message", 16, 0xff969696u}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_whats_new_title2", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title2_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title2_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_whats_new_title3", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message4", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message5", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message6", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message7", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message8", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message9", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title3_message10", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_whats_new_title4", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title4_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title4_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title4_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title4_message4", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title4_message5", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title4_message6", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title4_message7", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_whats_new_title5", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title5_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title5_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_whats_new_title6", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title6_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title6_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title6_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title6_message4", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title6_message5", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_whats_new_title7", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title7_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title7_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title8", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title8_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title8_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_whats_new_title9", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title9_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title9_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title9_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_whats_new_title10", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title10_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title10_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title10_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title10_message4", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title10_message5", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title10_message6", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title10_message7", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title10_message8", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_whats_new_title11", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title11_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title11_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_whats_new_title11_message3", 16, 0xffffffffu},
    {IT_END, NULL, 0, 0}};
static const Item k_help[] = {
    {IT_TEXT, "saveload_help_title", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title_message2", 16, 0xffffffffu},
    {IT_TEXT, "saveload_help_title_message3", 16, 0xff969696u}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_help_title2", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title2_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title2_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title2_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title2_message4", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title2_message5", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title2_message6", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_help_title3", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title3_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title3_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title3_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_help_title4", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message4", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message5", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message6", 16, 0xffffffffu},
    {IT_TEXT, "saveload_help_title4_message7", 16, 0xff969696u},
    {IT_TEXT, "saveload_help_title4_message8", 16, 0xff969696u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message9", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message10", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message11", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title4_message12", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT, "saveload_help_title5", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title5_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title5_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title5_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title5_message4", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT, "saveload_help_title5_message5", 16, 0xffffffffu},
    {IT_END, NULL, 0, 0}};
static const Item k_about[] = {
    {IT_IMAGE, NULL, 0, 0}, {IT_TEXT|IT_CENTER, "=Asphalt 8: Airborne Retry", 18, 0xffff9600u},
    {IT_GAP, NULL, 5, 0}, {IT_TEXT|IT_CENTER, "saveload_about_title_message", 16, 0xff969696u},
    {IT_GAP, NULL, 5, 0}, {IT_TEXT|IT_CENTER, "saveload_about_title_message2", 16, 0xffffffffu},
    {IT_TEXT|IT_CENTER, "=https://techboy1997mods.blogspot.com", 16, 0xffdce1ffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "=Techboy1997", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message2", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message4", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message5", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message6", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message7", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message8", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message9", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message11", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message12", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message13", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message14", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message15", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message10", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message16", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message17", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message19", 16, 0xffffffffu}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title2_message18", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title3", 18, 0xffff9600u}, {IT_GAP, NULL, 5, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title3_message", 16, 0xffffffffu}, {IT_GAP, NULL, 10, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title3_message3", 16, 0xffffffffu}, {IT_GAP, NULL, 15, 0},
    {IT_TEXT|IT_CENTER, "saveload_about_title4", 18, 0xffff9600u},
    {IT_END, NULL, 0, 0}};
